theme: jekyll-theme-tactile
title: Your awesome title
author: Joshua R
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Blog for posting game dev related content

# social links
twitter_username: jalejr # DO NOT include the @ character, or else the build will fail!
github_username:  jalejr # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
